### ISSUE TITLE
tomcat:run returning exception.

### ISSUE THREAD

**Issue by me4jobs19** [in28minutes/spring-master-class#4]
![error](https://user-images.githubusercontent.com/58166522/73520732-4975e600-442a-11ea-9b9b-4b1674d96406.png)

**Comment by JavatarSRB** [comment]
Looks like you need to set up java preferences > java check JRE > installed java JRE and also, update your maven project.

**Comment by me4jobs19** [comment]
Yes, its working now. Thank you.
